const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.Flash
	];
};
self.C3_JsPropNameTable = [
	{Пуля: 0},
	{СледитьЗа: 0},
	{машина: 0},
	{Клавиатура: 0},
	{дорога: 0},
	{спавнер_дорог: 0},
	{монета: 0},
	{Якорь: 0},
	{Текст: 0},
	{Мигание: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Мышь: 0},
	{Кнопка: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Кнопка2: 0},
	{кадр: 0},
	{r: 0},
	{g: 0},
	{b: 0}
];

self.InstanceType = {
	машина: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	дорога: class extends self.ISpriteInstance {},
	спавнер_дорог: class extends self.ISpriteInstance {},
	монета: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Кнопка2: class extends self.IButtonInstance {}
}